### ISSUE TITLE
Up and Running

### ISSUE THREAD

**Issue by semmiverian** [Wikiki/bulma-badge#1]
may i know what step should i follow to start using your bulma extension? 
i already try copy only the sass file and encounter some error like ` Index out of bounds for nth($list, $n)`

thanks for the help and thanks for the extension

**Comment by go4cas** [comment]
@semmiverian , here's how I got it working

- Clone the [bulma repo](https://github.com/jgthms/bulma)
- Under the `sass` folder, create a new folder called `extensions`
- In this new folder, create a new file `badge.sass`
- Copy the code form the `bulma-dage repo`'s [badge.sass](https://github.com/Wikiki/bulma-badge/blob/master/badge.sass) file into your new file
- In the same folder create a new file `_all.sass` (this is not required, but will help when you add more extensions)
- In this file add this code:
```
@charset "utf-8"
@import "badge.sass"
```
At the end of the `bulma.sass` file, add this line: `@import "sass/extensions/_all"`

Now, you can just build the bulma project with `npm run build`, and the output will be available in the `css folder`.

**Comment by semmiverian** [comment]
thanks for the guide man @go4cas it helps me a lot

**Comment by Wikiki** [comment]
Thanks @go4cas  for giving the answer. I'll add the process to follow into the README
