### ISSUE TITLE
Button badges don't overlap correctly

### ISSUE THREAD

**Issue by patrickblackjr** [Wikiki/bulma-badge#10]
They go behind the buttons that are next to it as [seen](https://wikiki.github.io/elements/badge/) on this page. They should overlap on the top.

**Comment by cirdog** [comment]
![bulma extension badge zlevel bug](https://user-images.githubusercontent.com/172924/51362458-b6178e80-1b0e-11e9-9fe4-b4cc6d4c6fed.png)

Yes, the z-level (?) of the badge is incorrect, or maybe some CSS3+ directives can fix it?

I'm on Chrome 71 windows x64, thanks!
