### ISSUE TITLE
publish version 3.0.0 to npm

### ISSUE THREAD

**Issue by mariannefeng** [Wikiki/bulma-badge#15]
I'm following documentation on usage here: https://demo.creativebulma.net/elements/badge/, which is referencing version 3.0.0, but the most up to date version in npm is 0.2.0. Would love if 3.0.0 was installable via npm! Pointing directly to the bulma-badge css file feels hacky as we're using react + bulma.

**Comment by Wikiki** [comment]
Hi,

npm has been updated.
