### ISSUE TITLE
cannot install via npm

### ISSUE THREAD

**Issue by mariannefeng** [Wikiki/bulma-badge#16]
I get the following message when trying to install via NPM (`npm i bulma-badge`): 

![Screen Shot 2019-03-08 at 12 37 49 PM](https://user-images.githubusercontent.com/10502722/54054507-34072600-419f-11e9-9f3f-d1fa198c6670.png)

**Comment by mariannefeng** [comment]
For anybody else who runs into this in the future....https://stackoverflow.com/questions/47074219/npm-err-unexpected-token-in-json-at-position-12842

Removing our package-lock.json did the trick!

**Comment by Wikiki** [comment]
thanks for the hint
