### ISSUE TITLE
It's posible to show badge on left side?

### ISSUE THREAD

**Issue by koddr** [Wikiki/bulma-badge#7]
Hello.

It's posible to show badge on button left side (up angle)? 
Would be great to have this feature 👍 

Thanks for awesome extension, btw!

**Comment by spacemudd** [comment]
```
<div class="button has-icon badge is-badge-danger is-badge-left" data-badge="1">
     <span class="icon"><i class="fa fa-inbox"></i></span>
</div>
```

**Comment by Wikiki** [comment]
Thanks @spacemudd

**Comment by koddr** [comment]
@spacemudd @Wikiki oh, great.. but would be great to place this info to docs 👍
